# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundle-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Rubocop
        run: rubocop
      - name: Install webpack
        run: rails webpacker:install
      - name: Run tests
        run: rspec ./spec
